# Activation extraction settings
extraction:
  # Model configuration
  #model_name: "meta-llama/Llama-2-7b-hf"
  # Alternative models:
  # - "meta-llama/Meta-Llama-3.1-70B"
  model_name: "meta-llama/Llama-3.1-8B"
  
  # Processing parameters
  batch_size: 16
  aggregation: "last"  # Options: "last", "mean", "max", "none"
  save_dir: "activation_datasets_2"
  
  # Quantization configuration
  quantization:
    load_in_4bit: true
    bnb_4bit_use_double_quant: false
    bnb_4bit_quant_type: "nf4"
    bnb_4bit_compute_dtype: "float16"  # Will be converted to torch.float16
  
  # Entity types and their templates
  entities:
    - entity_type: "atomic number_single"
      data_file: "periodic_table_dataset.csv"
      prompt_name: "1_templates"
      templates:
        - "In the periodic table, the atomic number of {Symbol}"